# Generated by Django 3.2.15 on 2022-09-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
    ]
