# Generated by Django 3.2.15 on 2022-09-09 17:06

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=220, unique=True)),
                ('content', models.TextField()),
                ('approve', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testim_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=220, unique=True)),
                ('blog_subtitle', models.TextField(blank=True)),
                ('blog_content', models.TextField()),
                ('blog_created_on', models.DateTimeField(auto_now_add=True)),
                ('blog_updated_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('blog_image_1', cloudinary.models.CloudinaryField(default='placeholder1', max_length=255, verbose_name='image')),
                ('blog_image_2', cloudinary.models.CloudinaryField(default='placeholder2', max_length=255, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Posted')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcc_post', to=settings.AUTH_USER_MODEL)),
                ('blog_favourite', models.ManyToManyField(blank=True, related_name='blog_favourite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-blog_created_on'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
                ('comment_body', models.TextField()),
                ('comment_approve', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='blogcc.blogpost')),
            ],
            options={
                'ordering': ['comment_created'],
            },
        ),
    ]
