# Generated by Django 3.2.15 on 2022-09-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogcc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment_approve',
            new_name='approve',
        ),
    ]
